//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessePlaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maße
    {
        public int Maße_ID { get; set; }
        public int Exponat_ID { get; set; }
        public decimal Länge_cm { get; set; }
        public decimal Breite_cm { get; set; }
        public decimal Höhe_cm { get; set; }
        public decimal Gewicht_kg { get; set; }
    
        public virtual Exponat Exponat { get; set; }
    }
}
