//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessePlaner
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestdbEntities : DbContext
    {
        public TestdbEntities()
            : base("name=TestdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Exponat> Exponat { get; set; }
        public virtual DbSet<Maße> Maße { get; set; }
        public virtual DbSet<Retoure> Retoure { get; set; }
        public virtual DbSet<Versand> Versand { get; set; }
        public virtual DbSet<Zubehör> Zubehör { get; set; }
    }
}
