//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessePlaner
{
    using System;
    using System.Collections.Generic;
    
    public partial class Versand
    {
        public int Messe_ID { get; set; }
        public int Exponat_ID { get; set; }
        public string Messe { get; set; }
        public string Land { get; set; }
        public string Ort { get; set; }
        public string Straße { get; set; }
        public string Hausnummer { get; set; }
        public string PLZ { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    
        public virtual Exponat Exponat { get; set; }
    }
}
